name: Archive Salesforce Data to Tracked Folders

on:
  workflow_dispatch:

permissions:
  # Gives the workflow permission to commit changes back to the repository
  contents: write

jobs:
  run-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate to Salesforce Org
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          SFDX_ORG_NAME: ${{ vars.SFDX_ORG_NAME }}
        run: |
          echo ">> The running salesforce org is ${{ vars.SFDX_ORG_NAME }}"
          echo "$SFDX_AUTH_URL" | sf org login sfdx-url --alias ${SFDX_ORG_NAME} --sfdx-url-stdin --set-default

      
      - name: Create Directory and Execute SOQL Query
        env:
          SFDX_ORG_NAME: ${{ vars.SFDX_ORG_NAME }}
        run: |
          # Execute and save query directly into that path
          echo ">> The running salesforce org is ${{ vars.SFDX_ORG_NAME }}"
          #sf data query --query "SELECT Id, Name, Industry FROM Account LIMIT 100" --target-org ${SFDX_ORG_NAME} --result-format csv > archive/${{ steps.vars.outputs.year }}/accounts_export_${{ steps.vars.outputs.timestamp }}.csv
          sf data:query --json -q "SELECT Id, GuestUserId FROM Site WHERE Name = 'MIAW_Experiencce_Site'" --o ${SFDX_ORG_NAME}
